### ISSUE TITLE
Compilation fails with `could not determine kind of name for C.nvmlDeviceCcuGetStreamState` error

### ISSUE THREAD

**Issue by csadorf** [klueska/nvkind#6]
Trying to compile this module fails with the following error:

```
$ make
go mod tidy
go mod vendor
go mod verify
all modules verified
go list -f '{{.Dir}}' "github.com/klueska/kind-with-gpus-examples"/... \
        | xargs gofmt -s -l -w
go build "github.com/klueska/kind-with-gpus-examples"/cmd/...
# github.com/NVIDIA/go-nvml/pkg/nvml
vendor/github.com/NVIDIA/go-nvml/pkg/nvml/nvml.go:2746:11: could not determine kind of name for C.nvmlDeviceCcuGetStreamState
vendor/github.com/NVIDIA/go-nvml/pkg/nvml/nvml.go:2755:11: could not determine kind of name for C.nvmlDeviceCcuSetStreamState
make: *** [Makefile:28: build] Error 1
```

I am not a familiar with go so I am not quite sure how to interpret this error. It seems obvious that failing to build github.com/klueska/kind-with-gpus-examples is the cause, which in turn might be caused by an incorrect nvml.h version? Any support would be much appreciated!

**Comment by klueska** [comment]
This was resolved offline. It turned out to be a misconfigured go installation.
